Fix typos and add some punctuation #76
spences10/last.scottspence.com pull request #77
Opened 2020-09-08 07:45 UTC by genesisgabiola

Aside from fixing typos and adding punction, I also remove "this time I'll need to move the created .ssh folder to" from line 319, which is cut or broken and I think it's duplicated on line around 514.

2020-09-08 08:19 UTC, genesisgabiola commented
Fix #76

2020-09-08 10:55 UTC, spences10 commented on content/posts/2020/08/26/wsl-bootstrap-2020/index.mdx
> +This time 'round it was just as confusing (for me) at the times
Remove this change, I don't use this punctuation

2020-09-08 10:56 UTC, spences10 commented on content/posts/2020/08/26/wsl-bootstrap-2020/index.mdx
> +If you don't have Windows Pro you should still be able to enable WSL 2
Unnecessary word, remove this please

2020-09-08 10:57 UTC, spences10 commented on content/posts/2020/08/26/wsl-bootstrap-2020/index.mdx
> +set of problems with line endings and file permissions.
Unnecessary punctuation, remove this please

2020-09-08 10:58 UTC, spences10 commented on content/posts/2020/08/26/wsl-bootstrap-2020/index.mdx
> +(yes) and `yarn add` to `ya`.
Thanks for this, much appreciated, multi cursor fail!

2020-09-08 10:59 UTC, spences10 commented on content/posts/2020/08/26/wsl-bootstrap-2020/index.mdx
> +sudo apt install unzip
Thanks for this 🙏

2020-09-08 11:00 UTC, spences10 requested changes
Thanks for this @genesisgabiola, please refer to my comments on parts I'm not willing to put in there and thanks for the typos.

2020-09-09 07:15 UTC, spences10 commented
Awesome! Thanks you so much @genesisgabiola 🙏

2020-09-09 07:22 UTC, merged

2020-09-09 07:25 UTC, genesisgabiola commented
> Awesome! Thanks you so much @genesisgabiola 🙏

I'm happy to contribute to your project 👍

2020-09-09 07:50 UTC, genesisgabiola commented
fix #76